package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/mindspec/mindspec/internal/brownfield"
	"github.com/spf13/cobra"
)

func resolveArchiveMode(mode string) (string, error) {
	mode = strings.TrimSpace(mode)
	if mode == "" {
		return "copy", nil
	}
	if mode != "copy" && mode != "move" {
		return "", fmt.Errorf("invalid --archive value %q: must be copy or move", mode)
	}
	return mode, nil
}

func validateMigrateApplyFlags(runID, archive string) (string, string, error) {
	runID = strings.TrimSpace(runID)
	if runID == "" {
		return "", "", fmt.Errorf("--run-id is required (generate one with 'mindspec migrate plan')")
	}
	resolvedArchive, err := resolveArchiveMode(archive)
	if err != nil {
		return "", "", err
	}
	return runID, resolvedArchive, nil
}

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Plan and apply brownfield documentation migration",
	Long: `Runs deterministic-first brownfield onboarding with explicit plan/apply phases.

Use 'mindspec migrate plan' to analyze and generate a reviewable plan,
then run 'mindspec migrate apply --run-id <id>' to execute that exact plan.`,
}

var migratePlanCmd = &cobra.Command{
	Use:   "plan",
	Short: "Analyze repository docs and generate migration plan artifacts",
	RunE: func(cmd *cobra.Command, args []string) error {
		runID, _ := cmd.Flags().GetString("run-id")
		jsonFlag, _ := cmd.Flags().GetBool("json")

		root, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getting working directory: %w", err)
		}

		report, err := brownfield.Run(root, brownfield.RunOptions{
			Apply: false,
			RunID: strings.TrimSpace(runID),
		})
		if report != nil {
			if jsonFlag {
				out, jsonErr := readMigrationArtifactJSON(root, report.RunID, "plan.json")
				if jsonErr != nil {
					return jsonErr
				}
				fmt.Println(out)
			} else {
				fmt.Println(report.FormatSummary())
				fmt.Println()
				fmt.Printf("Plan artifacts:\n  - %s\n  - %s\n",
					filepath.ToSlash(filepath.Join(".mindspec", "migrations", report.RunID, "plan.json")),
					filepath.ToSlash(filepath.Join(".mindspec", "migrations", report.RunID, "plan.md")),
				)
				fmt.Printf("Apply with: mindspec migrate apply --run-id %s\n", report.RunID)
			}
		}
		return err
	},
}

var migrateApplyCmd = &cobra.Command{
	Use:   "apply",
	Short: "Apply a previously generated migration plan",
	RunE: func(cmd *cobra.Command, args []string) error {
		runID, _ := cmd.Flags().GetString("run-id")
		archive, _ := cmd.Flags().GetString("archive")
		jsonFlag, _ := cmd.Flags().GetBool("json")

		runID, archive, err := validateMigrateApplyFlags(runID, archive)
		if err != nil {
			return err
		}

		root, err := os.Getwd()
		if err != nil {
			return fmt.Errorf("getting working directory: %w", err)
		}

		report, err := brownfield.Run(root, brownfield.RunOptions{
			Apply:       true,
			ArchiveMode: archive,
			RunID:       runID,
			Resume:      true,
		})
		if report != nil {
			if jsonFlag {
				out, jsonErr := readMigrationArtifactJSON(root, report.RunID, "apply.json")
				if jsonErr != nil {
					return jsonErr
				}
				fmt.Println(out)
			} else {
				fmt.Println(report.FormatSummary())
				fmt.Println()
				fmt.Printf("Migration apply completed (run-id=%s, archive=%s).\n", runID, archive)
			}
		}
		return err
	},
}

func readMigrationArtifactJSON(root, runID, name string) (string, error) {
	path := filepath.Join(root, ".mindspec", "migrations", runID, name)
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read migration artifact %s: %w", filepath.ToSlash(path), err)
	}
	return strings.TrimSpace(string(data)), nil
}

func init() {
	migratePlanCmd.Flags().String("run-id", "", "Optional run ID; defaults to UTC timestamp")
	migratePlanCmd.Flags().Bool("json", false, "Output migration plan report as JSON")

	migrateApplyCmd.Flags().String("run-id", "", "Run ID generated by 'mindspec migrate plan'")
	migrateApplyCmd.Flags().String("archive", "copy", "Archive mode: copy or move")
	migrateApplyCmd.Flags().Bool("json", false, "Output migration apply report as JSON")

	migrateCmd.AddCommand(migratePlanCmd)
	migrateCmd.AddCommand(migrateApplyCmd)
}
