package ownership

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// --- RenderStub (Req 8) ---

func TestRenderStub_SubstitutesCommandAndKeepsEmptyBody(t *testing.T) {
	t.Parallel()

	stub := string(RenderStub("mindspec domain add payments"))

	if !strings.HasPrefix(stub, "# Auto-generated by mindspec domain add payments on ") {
		t.Errorf("stub first line missing <command> substitution:\n%s", stub)
	}
	if !strings.HasSuffix(stub, "paths: []\n") {
		t.Errorf("stub body must end with the empty `paths: []` stub, got:\n%s", stub)
	}
	// ZFC: the framework never pre-fills a real claim. The only glob in
	// the stub is the spec-verbatim hand-edit example inside the comment.
	for _, line := range strings.Split(stub, "\n") {
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}
		if line != "paths: []" {
			t.Errorf("stub contains non-comment content beyond `paths: []`: %q", line)
		}
	}
}

func TestRenderStub_BodyIdenticalAcrossCommands(t *testing.T) {
	t.Parallel()

	a := string(RenderStub("mindspec doctor --fix"))
	b := string(RenderStub("mindspec domain add payments"))

	// Strip the variable first line (command + timestamp); everything
	// after must be byte-identical (Req 8: one helper, one variable).
	tailA := a[strings.Index(a, "\n"):]
	tailB := b[strings.Index(b, "\n"):]
	if tailA != tailB {
		t.Errorf("stub bodies differ beyond the first line:\n--- doctor ---\n%s\n--- domain add ---\n%s", tailA, tailB)
	}
}

// --- BuildPopulatePrompt (Req 10) ---

func TestBuildPopulatePrompt_NamesDomainAndManifestPath(t *testing.T) {
	t.Parallel()

	prompt := BuildPopulatePrompt("payments")

	required := []string{
		".mindspec/docs/domains/payments/OWNERSHIP.yaml",
		`the "payments" domain`,
		"overview.md",
		"architecture.md",
		"paths:",
		"exclude:",
		"HARD ERROR",
		"`viz`, `agentmind`, or `bench`",
		"The framework deliberately provides no pattern hints",
		"dead-manifest",
	}
	for _, r := range required {
		if !strings.Contains(prompt, r) {
			t.Errorf("populate prompt missing %q\n--- prompt ---\n%s", r, prompt)
		}
	}
}

func TestBuildPopulatePrompt_NoFrameworkProposedGlobs(t *testing.T) {
	t.Parallel()

	// ZFC negative assertion: the framework must NOT propose
	// `internal/<domain>/**` (the removed Req 13 heuristic) or any
	// pre-filled glob for the named domain.
	prompt := BuildPopulatePrompt("payments")

	banned := []string{
		"internal/payments/**",
		"internal/<domain>/**",
		"cmd/payments/**",
	}
	for _, b := range banned {
		if strings.Contains(prompt, b) {
			t.Errorf("populate prompt contains framework-proposed glob %q (ZFC violation)\n--- prompt ---\n%s", b, prompt)
		}
	}
}

// --- DomainsNeedingPopulate (Req 10 no-arg enumeration) ---

// writeDomain creates .mindspec/docs/domains/<name>/ with optional
// OWNERSHIP.yaml content (manifest omitted when content is "").
func writeDomain(t *testing.T, root, name, manifest string) {
	t.Helper()
	dir := filepath.Join(root, ".mindspec", "docs", "domains", name)
	if err := os.MkdirAll(dir, 0755); err != nil {
		t.Fatal(err)
	}
	if manifest != "" {
		if err := os.WriteFile(filepath.Join(dir, "OWNERSHIP.yaml"), []byte(manifest), 0644); err != nil {
			t.Fatal(err)
		}
	}
}

func TestDomainsNeedingPopulate_MissingAndEmptyStubOnly(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	writeDomain(t, root, "absent", "")                                           // missing manifest
	writeDomain(t, root, "stub", string(RenderStub("mindspec domain add stub"))) // empty stub
	writeDomain(t, root, "filled", "paths:\n  - internal/filled/**\n")           // populated

	got, err := DomainsNeedingPopulate(root)
	if err != nil {
		t.Fatalf("DomainsNeedingPopulate: %v", err)
	}
	want := []string{"absent", "stub"}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("DomainsNeedingPopulate = %v, want %v", got, want)
	}
}

func TestDomainsNeedingPopulate_NoDomainsDir(t *testing.T) {
	t.Parallel()

	got, err := DomainsNeedingPopulate(t.TempDir())
	if err != nil {
		t.Fatalf("DomainsNeedingPopulate: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("expected no domains, got %v", got)
	}
}

// --- BuildSourcePopulatePrompt (Req 12) ---

func TestBuildSourcePopulatePrompt_RequiredContent(t *testing.T) {
	t.Parallel()

	prompt := BuildSourcePopulatePrompt()

	required := []string{
		"source_globs:",
		".mindspec/config.yaml",
		"The framework deliberately provides no pattern hints",
		"unclaimed-source",
		"missing-source-globs",
	}
	for _, r := range required {
		if !strings.Contains(prompt, r) {
			t.Errorf("source-populate prompt missing %q\n--- prompt ---\n%s", r, prompt)
		}
	}

	// The spec-verbatim text wraps "FULLY REPLACES" across a line
	// break; assert against a whitespace-normalized view so the
	// coverage warning is pinned regardless of wrapping.
	flat := strings.Join(strings.Fields(prompt), " ")
	if !strings.Contains(flat, "FULLY REPLACES") {
		t.Errorf("source-populate prompt missing the FULLY REPLACES coverage warning\n--- prompt ---\n%s", prompt)
	}
}

func TestBuildSourcePopulatePrompt_NoPreFilledGlobs(t *testing.T) {
	t.Parallel()

	// ZFC negative assertion: no suggested glob values.
	prompt := BuildSourcePopulatePrompt()

	banned := []string{"cmd/**", "internal/**"}
	for _, b := range banned {
		if strings.Contains(prompt, b) {
			t.Errorf("source-populate prompt contains pre-filled glob %q (ZFC violation)\n--- prompt ---\n%s", b, prompt)
		}
	}
}
