// Package ownership provides the ZFC-compliant scaffolding and
// prompt-emission helpers for per-domain OWNERSHIP.yaml manifests and
// the repo-wide source_globs config field (spec 091).
//
// The framework's role here is purely mechanical: it writes empty
// stubs and prints templated prompts; it never proposes paths or
// globs. Which paths a domain owns — and which globs count as
// "source" — are semantic decisions the resident coding agent or the
// human operator makes by inspecting the repo (Zero Framework
// Cognition, ADR-0036).
package ownership

import (
	"strings"
	"time"
)

// stubTemplate is the spec 091 Requirement 8 empty-stub OWNERSHIP.yaml
// content, verbatim. The body (`paths: []`) is identical across all
// scaffolding sources; the leading comment's <command> token is the
// ONLY substitution parameter (the timestamp is computed at render
// time, not passed in). Do NOT copy this comment body anywhere else —
// RenderStub is the single templating helper for every stub writer
// (`mindspec doctor --fix` and `mindspec domain add <name>`; migrate
// needs no third variant because its stubs are written transitively
// via `domain add`).
const stubTemplate = `# Auto-generated by <command> on <RFC3339 timestamp>.
# mindspec deliberately does NOT guess which paths belong to
# the "<domain>" domain — that is a semantic decision a coding
# agent or human operator makes by inspecting the repo. See
# spec 086 / ADR-0031 for the schema and ADR-0036 for the
# Zero-Framework-Cognition rationale.
#
# To populate this manifest:
#   • Run ` + "`mindspec ownership populate <domain>`" + ` to emit an
#     agent prompt that proposes paths based on the actual
#     repo layout; or
#   • Edit the ` + "`paths:`" + ` list below by hand to list the source
#     globs that this domain owns (e.g. ` + "`internal/ledger/**`" + `
#     for a domain named "payments").
#
# Until populated, ` + "`mindspec doctor`" + ` will Warn ` + "`dead-manifest`" + `
# and — once ` + "`source_globs:`" + ` is populated in
# .mindspec/config.yaml (run ` + "`mindspec source populate`" + `) —
# the doc-sync gate will Warn ` + "`unclaimed-source`" + ` on any
# diff that touches source files this domain should claim.
paths: []
`

// RenderStub returns the Requirement 8 empty-stub OWNERSHIP.yaml
// content. generatedBy is the command line that produced the stub —
// the only variable in the comment (substitution table, spec 091
// Req 8): `mindspec doctor --fix` for the doctor fixer (Bead 4's call
// site) or `mindspec domain add <name>` for domain scaffolding. The
// `<domain>` tokens in the comment body stay literal by design — the
// comment is identical across all stubs except its first line.
func RenderStub(generatedBy string) []byte {
	out := strings.Replace(stubTemplate, "<command>", generatedBy, 1)
	out = strings.Replace(out, "<RFC3339 timestamp>", time.Now().UTC().Format(time.RFC3339), 1)
	return []byte(out)
}
