package redact

import (
	"errors"
	"fmt"
	"strings"
	"testing"

	"github.com/mrmaxsteel/mindspec/internal/config"
	"github.com/mrmaxsteel/mindspec/internal/next"
)

// The adversarial golden corpus (Req 1 / HC-1, the keystone). Fixtures
// are built from REAL mindspec error/recovery strings — the genuine
// guard.go ClaimFailure + worktree-add recipe are GENERATED by calling
// the exported formatters so the corpus tracks template drift; the
// complete.go-folded divergence:186 message and the %w Dolt-1105 chain
// are reconstructed verbatim from their source templates.
//
// Every fixture is fed through the redactor and asserted to leak ZERO
// of: absolute/relative paths, *.go tokens, spec slugs, branch names,
// bead ids, OWNERSHIP domain names, bead descriptions, or high-entropy
// runs. This test is wired as the HC-1 CI gate (it runs in the standard
// `go test ./...` job; ci.yml additionally lists it as a dedicated,
// non-skippable step).

// sensitive lists the tokens that MUST NOT survive redaction, per
// fixture. The mutation test (below) proves these are real by asserting
// the RAW fixture DOES contain them — so a neutered scrub goes RED.
type goldenFixture struct {
	name      string
	raw       string
	sensitive []string
	scrub     func(string) (string, bool) // Scrub or an err-chain wrapper
	// wantClassified asserts the fixture fully classifies (ok==true) — it
	// is neutralised by the passes, NOT merely dropped by the fail-closed
	// residual gate. This is what makes the gate FALSIFIABLE against a
	// neutered pass: a regressed pass that trips the drop-gate flips ok to
	// false and turns this assertion RED (a drop would otherwise mask the
	// regression as still-leak-free).
	wantClassified bool
}

func claimFailureFixture(t *testing.T) goldenFixture {
	t.Helper()
	root := "/Users/maxsteel/replit/mindspec"
	cfg := config.DefaultConfig()
	beadID := "mindspec-cdk8.1"
	specID := "094-self-improvement-loop"
	claimErr := errors.New("Dolt Error 1105: event recording failed")
	err := next.ClaimFailure(root, cfg, beadID, specID, claimErr)
	return goldenFixture{
		name: "guard.ClaimFailure recovery recipe",
		raw:  err.Error(),
		sensitive: []string{
			"/Users/maxsteel", "maxsteel", "replit/mindspec",
			"mindspec-cdk8.1", "bead/mindspec-cdk8.1",
			"094-self-improvement-loop", "spec/094-self-improvement-loop",
			"worktree-mindspec-cdk8.1", "worktree-spec-094",
		},
		scrub:          Scrub,
		wantClassified: true,
	}
}

func worktreeSetupFixture(t *testing.T) goldenFixture {
	t.Helper()
	root := "/home/agent/work/mindspec"
	cfg := config.DefaultConfig()
	err := next.WorktreeSetupFailure(root, cfg, "mindspec-zzz9", "091-ownership-discovery",
		errors.New("fatal: a branch named already exists"))
	return goldenFixture{
		name: "guard.WorktreeSetupFailure recipe",
		raw:  err.Error(),
		sensitive: []string{
			"/home/agent", "agent/work", "mindspec-zzz9",
			"bead/mindspec-zzz9", "091-ownership-discovery",
			"spec/091-ownership-discovery", "worktree-mindspec-zzz9",
		},
		scrub:          Scrub,
		wantClassified: true,
	}
}

// divergenceFolded reconstructs divergence.go:186 (adr-divergence-unowned)
// VERBATIM from its template, folded the way joinResultErrorMessages
// (complete.go) renders it ("[name] message") and wrapped by
// adrDivergenceFailure ("adr-divergence: ...").
func divergenceFoldedFixture() goldenFixture {
	relPath := "internal/validate/divergence.go"
	domains := "[core git state]"
	inner := fmt.Sprintf(
		"file %s is not claimed by any OWNERSHIP.yaml for the spec's impacted domains %s; add it to an existing manifest or create a new domain dir at .mindspec/docs/domains/<name>/OWNERSHIP.yaml",
		relPath, domains)
	folded := "[adr-divergence-unowned] " + inner
	full := "adr-divergence: " + folded
	return goldenFixture{
		name: "divergence.go:186 folded by complete.go",
		raw:  full,
		sensitive: []string{
			"internal/validate/divergence.go", "divergence.go",
			"[core git state]", "core git state",
			".mindspec/docs/domains",
		},
		scrub:          Scrub,
		wantClassified: true,
	}
}

// doltChainFixture is the %w-wrapped Dolt-1105 chain carrying a bead
// DESCRIPTION (free text). It is scrubbed via ScrubError (the %w rule),
// which unwraps to the sentinel code and discards the wrapped message.
func doltChainFixture() goldenFixture {
	desc := "Redaction library plus adversarial golden corpus and version helper, the PRIVACY KEYSTONE touching internal/redact and bead mindspec-cdk8.1"
	inner := fmt.Errorf("Dolt Error 1105: Out of range value for column description at row 1: %s", desc)
	chain := fmt.Errorf("recording bead event: %w", inner)
	return goldenFixture{
		name: "%w-wrapped Dolt-1105 chain carrying a bead description",
		raw:  chain.Error(),
		sensitive: []string{
			"PRIVACY KEYSTONE", "Redaction library plus adversarial",
			"internal/redact", "mindspec-cdk8.1",
		},
		scrub:          func(s string) (string, bool) { return ScrubError(chain) },
		wantClassified: true,
	}
}

func goldenFixtures(t *testing.T) []goldenFixture {
	t.Helper()
	return []goldenFixture{
		claimFailureFixture(t),
		worktreeSetupFixture(t),
		divergenceFoldedFixture(),
		doltChainFixture(),
	}
}

// TestGoldenCorpus_ZeroLeakage is the HC-1 gate: every real-string
// fixture redacts with ZERO leakage of any sensitive token.
func TestGoldenCorpus_ZeroLeakage(t *testing.T) {
	for _, f := range goldenFixtures(t) {
		t.Run(f.name, func(t *testing.T) {
			clean, ok := f.scrub(f.raw)
			if f.wantClassified && !ok {
				// A regressed pass that trips the residual drop-gate lands
				// here (ok=false) — the gate is falsifiable, not just
				// declaratively "leak-free via drop".
				t.Errorf("fixture %q dropped (ok=false); want fully classified "+
					"(a scrub pass likely regressed): redacted=%q", f.name, clean)
			}
			for _, s := range f.sensitive {
				if strings.Contains(clean, s) {
					t.Errorf("LEAK in %q:\n token: %q\n redacted: %q\n raw: %q",
						f.name, s, clean, f.raw)
				}
			}
			// Defense-in-depth: also assert no generic dangerous shape
			// survives (catches tokens we did not explicitly enumerate).
			if hasResidualLeak(clean) {
				t.Errorf("residual dangerous pattern survived in %q: %q", f.name, clean)
			}
		})
	}
}

// TestGoldenCorpus_MutationDetectsLeak is the FALSIFIABLE / mutation
// assertion (AC (a)): the corpus gate is NOT vacuous. For every fixture
// the RAW (un-redacted) string DOES contain its sensitive tokens — so if
// redaction were neutered to identity, TestGoldenCorpus_ZeroLeakage would
// go RED. This test fails the build if a fixture's sensitive list is
// itself wrong (a token not actually present in the raw string), which
// would silently make the zero-leakage assertion pass for free.
func TestGoldenCorpus_MutationDetectsLeak(t *testing.T) {
	for _, f := range goldenFixtures(t) {
		t.Run(f.name, func(t *testing.T) {
			found := 0
			for _, s := range f.sensitive {
				if strings.Contains(f.raw, s) {
					found++
				}
			}
			if found == 0 {
				t.Fatalf("vacuous fixture %q: NONE of its sensitive tokens "+
					"appear in the raw string — the zero-leakage gate would "+
					"pass trivially", f.name)
			}
		})
	}
}

// TestGoldenCorpus_DeliberatelyLeakyFixtureFails is the explicit
// mutation/negative case (AC: a deliberately-leaky fixture must make the
// test FAIL). It feeds a fixture whose "redactor" is the identity
// function (a neutered scrub) and asserts the SAME zero-leakage check
// reports a leak — proving the gate catches a neutered scrub.
func TestGoldenCorpus_DeliberatelyLeakyFixtureFails(t *testing.T) {
	leaky := goldenFixture{
		name:      "neutered scrub (identity)",
		raw:       "fatal at /Users/maxsteel/secret/path and bead mindspec-cdk8.1",
		sensitive: []string{"/Users/maxsteel", "mindspec-cdk8.1"},
		scrub:     func(s string) (string, bool) { return s, true }, // NEUTERED
	}
	clean, _ := leaky.scrub(leaky.raw)
	leaked := false
	for _, s := range leaky.sensitive {
		if strings.Contains(clean, s) {
			leaked = true
		}
	}
	if !leaked {
		t.Fatal("a neutered (identity) scrub did NOT trip the leakage check — " +
			"the golden-corpus gate is not falsifiable")
	}
}
